freebsd_instance:
  image_family: freebsd-13-0

first_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  files_artifacts:
    path: "files/*"
  foo_script:
    - pkg install -y curl
    - mkdir files
    - echo foobar > files/foo
    - echo froofroo > files/bar
    - tar -czf files.txz files
    - curl -s -X POST --data-binary @files.txz http://${CIRRUS_HTTP_CACHE_HOST}/files.txz
second_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  depends_on:
    - first
  foo2_script:
    - pkg install -y curl
    - curl -o files.txz http://${CIRRUS_HTTP_CACHE_HOST}/files.txz
    - tar -xzf files.txz
    - ls -l
    - cat files/foo
