freebsd_instance:
  image_family: freebsd-13-0

first_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  foo_script:
    - mkdir files
    - echo foobar > files/foo
    - echo froofroo > files/bar
  files_artifacts:
    path: "files/*"
second_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  depends_on:
    - first
  foo2_script:
    - pkg install -y wget
    - wget https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}>/files.zip
    - unzip files.zip
    - ls -l
    - cat files/foo
